name: recco
description: Recco is a personalized, and user-friendly approach to health and wellness recommendations based on users' unique interests, motivations, and health behaviors.
version: 1.1.0

homepage: "https://github.com/sf-recco/flutter-showcase"

environment:
  sdk: '>=2.18.4 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.significo.recco
        pluginClass: ReccoPlugin
      ios:
        pluginClass: ReccoPlugin
