name: recco
description: A Flutter plugin for both iOS and Android recco-sdk.
version: 0.0.1

homepage: "https://github.com/sf-recco/flutter-showcase"

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.significo.recco
        pluginClass: ReccoPlugin
      ios:
        pluginClass: ReccoPlugin
