// Autogenerated from Pigeon (v10.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ShadowflightApi {
  func login(userId: String) throws
  func logout() throws
  func navigateToDashboard() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ShadowflightApiSetup {
  /// The codec used by ShadowflightApi.
  /// Sets up an instance of `ShadowflightApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ShadowflightApi?) {
    let loginChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ShadowflightApi.login", binaryMessenger: binaryMessenger)
    if let api = api {
      loginChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let userIdArg = args[0] as! String
        do {
          try api.login(userId: userIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loginChannel.setMessageHandler(nil)
    }
    let logoutChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ShadowflightApi.logout", binaryMessenger: binaryMessenger)
    if let api = api {
      logoutChannel.setMessageHandler { _, reply in
        do {
          try api.logout()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      logoutChannel.setMessageHandler(nil)
    }
    let navigateToDashboardChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ShadowflightApi.navigateToDashboard", binaryMessenger: binaryMessenger)
    if let api = api {
      navigateToDashboardChannel.setMessageHandler { _, reply in
        do {
          try api.navigateToDashboard()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      navigateToDashboardChannel.setMessageHandler(nil)
    }
  }
}
