// Autogenerated from Pigeon (v10.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by ReccoApi.
NSObject<FlutterMessageCodec> *ReccoApiGetCodec(void);

@protocol ReccoApi
- (void)loginUserId:(NSString *)userId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)logoutWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)navigateToDashboardWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void ReccoApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ReccoApi> *_Nullable api);

NS_ASSUME_NONNULL_END
